### ISSUE TITLE
Create tests, improve docs and License

### ISSUE THREAD

**Issue by franciscop** [teologov/path-to-regexp-wrap#1]
Hi @teologov , from looking at the source code this library is just what I needed and was making but I'd love for it to have some tests. Is the library still being maintained? Can I work on that and make a PR?

I made the same assumptions in my code (return false it it doesn't match), so I would also add that to the readme.

Lastly, I see that the license in the `package.json` is MIT so I'd also like to add a LICENSE file on the project root.

**Comment by teologov** [comment]
Hi, @franciscop! 
I still use this library in some projects, but unfortunately, I don't have enough time to cover it with tests. 

Feel free to create a pull request! I will really appreciate it. 

Yes, the license if MIT, I will add a LICENSE file. 

Thanks for pointing it out.

**Comment by teologov** [comment]
UPD: I added a LICENSE file to the root of the project. Also, I added a scaffolding for the tests. 
I'll try to find some time next week to work on the tests.

Thanks again for bringing back to life this tiny project!
